// Svelte/todoapp/client/src/components/DoneTab.svelte
<script>
    import { dones } from '../store/store.js';
    import Element from './Element.svelte';

    var donesValues;
    dones.subscribe(value => {
        donesValues = value;
    });

</script>

<div class="grid grid-cols-1 mx-10 my-6">
    {#each donesValues as done }
        <Element todo={done}/>
    {/each}
</div>

// React/client/src/components/DoneTab.jsx
import Element from './Element';
import { useSelector } from "react-redux";

export default function DoneTab() {
    const dones = useSelector((state) => state.dones);

    return(
        <div className="grid grid-cols-1 mx-10 my-6">
            {
                dones.map((done, index) => {
                    return <Element key={done._id} todo={done}/>;
                })
            }
        </div>
    );
}
