// Angular/client/src/app/components/Tabs.ts
import { Component } from '@angular/core';
import { TodoService } from "../todo.service";
import { Observable } from 'rxjs';

@Component({
  selector: 'app-tabs',
  template: `
    <div class="bg-white">
    <div class="sticky top-[70px] z-50 bg-white border-b border-teal-500">
        <ul class="flex flex-row flex-nowrap -mb-px text-sm font-medium text-center text-teal-500">
        <li *ngFor="let tab of tabConfig" class="w-full mr-2">
            <button (click)="setActiveTab(tab.id)" [ngClass]="(activeTab$ | async) === tab.id? 'active' : 'inactive'" class="flex w-full justify-center p-4 border-b-4 rounded-t-lg hover:text-teal-300">
            {{ tab.label }}
            </button>
        </li>
        </ul>
    </div>
    <div class="w-full">
        <ng-container *ngFor="let tab of tabConfig">
          <ng-container *ngIf="(activeTab$ | async) === tab.id">
              <app-todo-tab *ngIf="tab.id === 1"></app-todo-tab>
              <app-done-tab *ngIf="tab.id === 2"></app-done-tab>
          </ng-container>
        </ng-container>
    </div>
    </div>
  `,
  styles: [`
    .active {
        @apply border-teal-500;
    }

    .inactive {
        @apply border-transparent;
    }
  `]
})
export class TabsComponent {
  tabConfig = [
    { id: 1, label: "To do" },
    { id: 2, label: "Done" }
  ];

  activeTab$: Observable<number>;

  constructor(private todoService: TodoService) {
    this.activeTab$ = this.todoService.getActiveTab();
  }

  setActiveTab(tabId: number): void {
    this.todoService.setActiveTab(tabId);
  }
}

// Svelte/todoapp/client/src/components/Tabs.svelte
<script>
    import { activeTab } from "../store/store";
    import TodoTab from "./TodoTab.svelte";
    import DoneTab from "./DoneTab.svelte";

    var tabConfig = [
        { id: 1, label:"To do", tab: TodoTab },
        { id: 2, label:"Done", tab: DoneTab }
    ];

    var activeTabValue;
    activeTab.subscribe(value => {
        activeTabValue = value;
    });

    let setActiveTab = (tab) => {
        activeTab.set(tab);
    };

</script>

<div class="bg-white">
    <div class="sticky top-[70px] z-50 bg-white border-b border-teal-500">
        <ul class="flex flex-row flex-nowrap -mb-px text-sm font-medium text-center text-teal-500">
            {#each tabConfig as currentTab }
                <li class="w-full mr-2">
                    <button on:click={() => setActiveTab(currentTab.id)} class="{activeTabValue === currentTab.id ? 'active ' : ''}flex w-full justify-center p-4 border-b-4 border-transparent rounded-t-lg hover:text-teal-300">
                        { currentTab.label }
                    </button>
                </li>
            {/each}
        </ul>
    </div>
    <div class="w-full">
        {#each tabConfig as currentTab }
            {#if currentTab.id === activeTabValue }
                <svelte:component this={currentTab.tab}/>
            {/if}
        {/each}
    </div>
</div>

<style>
    .active {
        @apply border-teal-500;
    }
</style>
