// React/client/src/components/TodoTab.jsx
import Element from './Element';
import { useSelector } from "react-redux";

export default function TodoTab() {
    const todos = useSelector((state) => state.todos);

    return(
        <div className="grid grid-cols-1 mx-10 my-6">
            {
                todos.map((todo, index) => {
                    return <Element key={todo._id} todo={todo}/>;
                })
            }
        </div>
    );
}

// Svelte/todoapp/client/src/components/TodoTab.svelte
<script>
    import { todos } from '../store/store.js';
    import Element from './Element.svelte';

    var todosValues;
    todos.subscribe(value => {
        todosValues = value;
    });

</script>

<div class="grid grid-cols-1 mx-10 my-6">
    {#each todosValues as todo }
        <Element todo={todo}/>
    {/each}
</div>
